[theme]
primaryColor="#1E1E1E"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#000000"
font="sans serif"

[server]
headless = true
enableCORS=false

[ui]
# Hide the menu hamburger
hideMenu = true
# Hide the “Made with Streamlit” footer
hideFooter = true
